-- Users
CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	name VARCHAR(255) NULL,
	subscription_plan ENUM('free', 'premium') NOT NULL DEFAULT 'free',
	storage_used BIGINT UNSIGNED NOT NULL DEFAULT 0,
	storage_limit BIGINT UNSIGNED NOT NULL DEFAULT 5368709120, -- 5GB en bytes
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Documents
CREATE TABLE IF NOT EXISTS documents (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	filename VARCHAR(255) NOT NULL,
	mime_type VARCHAR(100) NOT NULL,
	byte_size BIGINT UNSIGNED NOT NULL,
	storage_path VARCHAR(500) NOT NULL,
	iv VARBINARY(16) NOT NULL,
	auth_tag VARBINARY(16) NOT NULL,
	status ENUM('processing','ready','error') NOT NULL DEFAULT 'processing',
	provider VARCHAR(255) NULL,
	invoice_number VARCHAR(100) NULL,
	currency VARCHAR(10) NULL,
	amount DECIMAL(12,2) NULL,
	issue_date DATE NULL,
	meta JSON NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- OCR results
CREATE TABLE IF NOT EXISTS ocr_results (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	document_id BIGINT UNSIGNED NOT NULL,
	text LONGTEXT NULL,
	json JSON NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tags
CREATE TABLE IF NOT EXISTS tags (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Document-Tag relation
CREATE TABLE IF NOT EXISTS document_tags (
	document_id BIGINT UNSIGNED NOT NULL,
	tag_id BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (document_id, tag_id),
	FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sessions (optional for refresh tokens if stored)
CREATE TABLE IF NOT EXISTS sessions (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	refresh_token_hash VARCHAR(255) NOT NULL,
	expires_at DATETIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	INDEX (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 